name: Doxygen dokumentacija

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Preuzmi repozitorij
        uses: actions/checkout@v4

      - name: Instaliraj Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generiraj Doxygen dokumentaciju
        run: cd Lab1 && doxygen Doxyfile

      - name: Objavi na GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Lab1/docs/html
